# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Manuel\Documents\Projects\DataStructureVisualizer\frontend\ui_files\mainmenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 599)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(10, 10, 561, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(60, 160, 201, 171))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.merge_button = QtWidgets.QPushButton(self.widget)
        self.merge_button.setObjectName("merge_button")
        self.verticalLayout.addWidget(self.merge_button)
        self.selection_button = QtWidgets.QPushButton(self.widget)
        self.selection_button.setObjectName("selection_button")
        self.verticalLayout.addWidget(self.selection_button)
        self.insertion_button = QtWidgets.QPushButton(self.widget)
        self.insertion_button.setObjectName("insertion_button")
        self.verticalLayout.addWidget(self.insertion_button)
        self.quick_button = QtWidgets.QPushButton(self.widget)
        self.quick_button.setObjectName("quick_button")
        self.verticalLayout.addWidget(self.quick_button)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Selecciona el algoritmo que deseas visualizar:"))
        self.merge_button.setText(_translate("MainWindow", "Merge Sort"))
        self.selection_button.setText(_translate("MainWindow", "Selection Sort"))
        self.insertion_button.setText(_translate("MainWindow", "Insertion Sort"))
        self.quick_button.setText(_translate("MainWindow", "Quick Sort"))
